version: "3"
 
services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - ./postgres:/var/lib/postgresql/data
 
  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "8080:3000"
    volumes:
      - .:/onebitexchange

